unstable_features = true

hard_tabs = true
tab_spaces = 4
max_width = 120

indent_style = "Block"
force_multiline_blocks = false
brace_style = "PreferSameLine"

wrap_comments = true

format_macro_matchers = true
format_macro_bodies = true

use_small_heuristics = "Max"
use_field_init_shorthand = true

fn_args_density = "Tall"
where_single_line = true
fn_single_line = true
struct_lit_single_line = true
empty_item_single_line = true
match_arm_blocks = false
overflow_delimited_expr = true
